### ISSUE TITLE
License

### ISSUE THREAD

**Issue by mekhanique** [sergueik/serverspec_custom_types#1]
Hi,

Would you mind providing an open source license for this project?  Preferably something like Apache 2.0, MIT or BSD?  I'd like to use this for some of my work, but I can't without a defined license.  Thanks!

**Comment by sergueik** [comment]
Hello @mekhanique

Thanks for inquiring, sorry for the delay

Added MIT LIICENSE


Let me know if you need any help or asssistance using the code. 

Seguei Kouzmine

**Comment by mekhanique** [comment]
That was super fast!  Thanks!
